<?php

namespace Tadcms\Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tadcms\Services\UserService;

class UserTest extends TestCase
{
    use RefreshDatabase;
    
    /**
     * @var UserService $userService
     * */
    protected $userService;
    
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    
        $this->userService = app(UserService::class)->make();
    }
    
    public function testCreateUser() {
        $factory = factory(\App\User::class)->make();
        $user = $this->userService->create($factory->getAttributes());
        $this->assertEquals($factory->name, $user->name);
    }
    
    public function testUpdateUser() {
        $factory = factory(\App\User::class)->create();
        $factory2 = factory(\App\User::class)->make();
        
        $user = $this->userService->update($factory->id,
            $factory2->getAttributes());
        $this->assertEquals($factory2->name, $user->name);
    }
    
    public function testDeleteUser() {
        $factory = factory(\App\User::class)->create();
    
        $result = $this->userService->delete($factory->id);
    
        $this->assertTrue($result);
    }
}
